### PR TITLE
fix: closes #141

### LINKED ISSUE #141: Skill localizations not correct for custom skills
When custom skills are levelled up, the localizations are not correct on the message displayed on the screen.

The `RaiseSkill` function displays a message like so:
```cs
this.m_player.Message((int) level == 0 ? MessageHud.MessageType.Center : MessageHud.MessageType.TopLeft, "$msg_skillup $skill_" + skill.m_info.m_skill.ToString().ToLower() + ": " + (object) (int) skill.m_level, 0, skill.m_info.m_icon);
```
which attempts to use the localization for the skill's ID

image

### PR DESCRIPTION
**Pull request by paddywaan**
Queries our own collection instead of the games, or returns default.

### CODE REVIEW

File: TestMod/TestMod.cs [hunk 1]
```diff
@@ -272,7 +285,7 @@ private void AddSkills()
             });
 
             // Test adding skills from JSON
-            SkillManager.Instance.AddSkillsFromJson("TestMod/Assets/skills.json");
+            //SkillManager.Instance.AddSkillsFromJson("TestMod/Assets/skills.json");
```
Comment (raduschirliu) [inline TestMod/TestMod.cs]: Shouldn't we leave this in to test the JSON skills as well?

**Review by raduschirliu — APPROVED** [review]

File: TestMod/TestMod.cs (hunk 1 above)
Comment (paddywaan) [reply TestMod/TestMod.cs]: my bad, nicely spotted

**Review by sirskunkalot — APPROVED** [review]
